tap_install:
  values:

    api_portal:
      apiPortalServer:
        sourceUrls: https://api-auto-registration.perfect300rock.com/openapi

    api_auto_registration:
      tap_gui_url: https://tap-gui.perfect300rock.com/
      route_provider:
        spring_cloud_gateway:
          scg_openapi_service_url: http://scg-openapi-service.spring-cloud-gateway.svc.cluster.local

    local_source_proxy:
      repository: reg.perfect300rock.com/tapdev/lsp-source
      push_secret:
       name: lsp-push-credentials
       namespace: tap-install
       create_export: true
      
      pull_secret:
       name: lsp-pull-credentials
       namespace: tap-install
       create_export: true

    appsso:
      default_workload_domain_template: "{{.Name}}.{{.Domain}}"
      
    contour:
      envoy:
        service:
          type: LoadBalancer
    
    #tap_telemetry:
    #  installed_for_vmware_internal_use: true
    
    grype:
      namespace: workloads
      targetImagePullSecret: registry-credentials
    
    profile: full
    ceip_policy_disclosed: true # Installation fails if this is set to 'false'
    
    cnrs:
      domain_name: perfect300rock.com
      domain_template: "{{.Name}}.{{.Domain}}"
      ingress_issuer: letsencrypt-prod
    
    accelerator:
      ingress:
        include: true
        enable_tls: true
      tls:
        secret_name: accelerator-cert
        namespace: accelerator-system
      operation_mode: kubernetes
    
    buildservice:
      kp_default_repository: "reg.perfect300rock.com/tapdev/build-service"
      #exclude_dependencies: true
    
    #supply_chain: testing
    supply_chain: testing_scanning
    #supply_chain: basic
    
    shared:
      ingress_domain: perfect300rock.com
      ingress_issuer: letsencrypt-prod
    
    #ootb_supply_chain_testing:
    ootb_supply_chain_testing_scanning:
    #ootb_supply_chain_basic:
      registry:
        server: "reg.perfect300rock.com"
        repository: "tapdev/supply-chain"
      gitops:
    #    ssh_secret: ""
        ssh_secret: "tap-play-gitops-secret"
    #     ssh_secret: "tap-gitlab-secret"
    #    server_address: https://github.com/
    #    repository_owner: gm2552
    #    repository_name: tap-play-gitops    
    #    branch: main
    #    commit_strategy: pull_request
    #    pull_request:
    #      server_kind: github
    #      commit_branch: ""
    #
    #      pull_request_title: ready for review
    #      pull_request_body: generated by supply chain
      cluster_builder: default
    
    tap_gui:
      tls:
        namespace: tap-gui
        secretName: tap-gui-cert
      service_type: ClusterIP
      ingressEnabled: "true"
      ingressDomain: "perfect300rock.com"
      app_config:
        app:
          baseUrl: https://tap-gui.perfect300rock.com
#        catalog:
#          locations:
#            - type: url
#              target: https://github.com/gm2552/tap-blank-catalog/blob/main/catalog-info.yaml
            # Or use a custom file format and location
            #- type: github-discovery
            #  target: https://github.com/gm2552/*/blob/-/catalog/catalog-info.yaml
        backend:
          baseUrl: https://tap-gui.perfect300rock.com
          cors:
            origin: https://tap-gui.perfect300rock.com
          reading:
            allow:
              - host: '*.perfect300rock.com'
              - host: 'hungryman-search.workloads'
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: 0614c6009639e1bc534c
                clientSecret: db7fbcc1b5cf43941ea42abb365387ad89617344
#        integrations:
#          github:
#            - host: github.com
#              token: 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               
#        proxy:
#          /metadata-store:
#            target: https://metadata-store.perfect300rock.com/api/v1
#            changeOrigin: true
#            secure: false
#            headers:
#              Authorization: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJjbUNlVElSNk1XZXlXU2g4eWlkeDhKTGNIajYzRjlZbUZDRmFOQW96SE0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjEyYWVmMzYzLTZlZDYtNGVhMS05NTNjLTc3NzExZTUzN2Q4MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.iF-bORgRb0k8Qnw9sgBz2uTCILEgnk2NGAAf9UW_Psyqo3DpEU1OnUanlzBxJtFIAdZhcUOii4Rxtm_-y8P4d8IdWrzL3Z2LXw9S1yYENMv7fClCnMcXI6aUCZic76i_S4nnb839E9DNdhS7-amzBlcGj6YakXr_bPS-Nuh844aWaOtlP_P3TjWpsVzQ5dRN9-azW3PvcNV8F0AE5_MJF_rySkSZeek6zQ-_3njEa_KWAxxEAy2AFRld1MJktzruY30NuvJ70N2eQcq8FNzKud4bcX4b8ewOT5QehktRWj5JBkfYBdHqn_aK2h_Jbx8fN_bCgid5HWqpJTwhEUNHaA"
#              X-Custom-Source: project-star
    
    metadata_store:
      ns_for_export_app_cert: "*"
      app_service_type: ClusterIP
#      ingress_domain: "perfect300rock.com"
#      ingress_enabled: "true"
    
#    scanning:
#      metadataStore:
#        url: ""
#      caSecret:
#        name: app-tls-cert
#        importFromNamespace: metadata-store

#    learningcenter:
#      ingressSecret: 
#        secretName: learning-center-cert
#      ingressClass:  contour
    
    excluded_packages:
      - snyk.scanning.apps.tanzu.vmware.com
      - prometheus.community.tanzu.vmware.com
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com

